### Test the National ID API without Authentication
POST http://localhost:8000/api/national-id/
Content-Type: application/json

{
  "national_id": "29001011234567"
}

### Test the National ID API with Authentication
POST http://localhost:8000/api/national-id/ HTTP/1.1
Content-Type: application/json
Authorization: Api-Key {{API_KEY}}

{
  "national_id": "29001011234567"
}

### Test with Invalid National ID
POST http://localhost:8000/api/national-id/
Content-Type: application/json
Authorization: Api-Key 


{
  "national_id": "12345678901234"
}
